# ====================
# Site settings
# ====================
title: Navya IRL
email: navya.agarwal.in@gmail.com
author: Navya Agarwal

keywords: Navya Agarwal, software, code, projects, AI experiments, web stuff, learning, mistakes, thinking out loud, dev life
description: "This is me putting my code, projects, ideas, and experiments online. Stuff I build, things I learn, and random thoughts I want to keep track of as I go through life."

github:
  url: "https://navyagarwal.github.io"

url: "http://localhost:4000"
baseurl: ""  # works locally

header: images/logo_light.png

# ====================
# Build settings
# ====================
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

feed:
  path: atom.xml

sass:
  style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

# ====================
# SEO & Analytics
# ====================

# Google Analytics (replace with your tracking ID if you want analytics)
google_universal_analytics: "G-FB371FE8P8"
google_universal_analytics_cookiedomain: auto

# Twitter Cards
twitter_user: "@Navya_Agarwal_"
twitter_card: true
twitter_image: images/logo_light.png